# yaml-language-server: $schema=https://raw.githubusercontent.com/optionfactory/pinch/refs/heads/master/schema/pinch-v1.schema.json
project:
  name: "Pinch Project"
vars:
  env: "dev"
processes:
  - title: "Backend"
    run: "cargo run"
    cwd: "{{pwd}}/backend"
  - title: "Frontend"
    run: "npm run dev"
    cwd: "{{ pwd }}/frontend"
    mode: "tui"
